export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

export const ORDER_LIST_ALL_REQUEST = "ORDER_LIST_ALL_REQUEST";
export const ORDER_LIST_ALL_SUCCESS = "ORDER_LIST_ALL_SUCCESS";
export const ORDER_LIST_ALL_FAIL = "ORDER_LIST_ALL_FAIL";

export const ORDER_STATUS_UPDATE_REQUEST = "ORDER_STATUS_UPDATE_REQUEST";
export const ORDER_STATUS_UPDATE_SUCCESS = "ORDER_STATUS_UPDATE_SUCCESS";
export const ORDER_STATUS_UPDATE_FAIL = "ORDER_STATUS_UPDATE_FAIL";
export const ORDER_STATUS_UPDATE_RESET = "ORDER_STATUS_UPDATE_RESET";

export const ORDER_REMINDER_SET_REQUEST = "ORDER_REMINDER_SET_REQUEST";
export const ORDER_REMINDER_SET_SUCCESS = "ORDER_REMINDER_SET_SUCCESS";
export const ORDER_REMINDER_SET_FAIL = "ORDER_REMINDER_SET_FAIL";
export const ORDER_REMINDER_SET_RESET = "ORDER_REMINDER_SET_RESET";

export const ORDER_REMINDERS_ACTIVE_REQUEST = "ORDER_REMINDERS_ACTIVE_REQUEST";
export const ORDER_REMINDERS_ACTIVE_SUCCESS = "ORDER_REMINDERS_ACTIVE_SUCCESS";
export const ORDER_REMINDERS_ACTIVE_FAIL = "ORDER_REMINDERS_ACTIVE_FAIL";

export const ORDER_REMINDER_MARK_SHOWN_REQUEST = "ORDER_REMINDER_MARK_SHOWN_REQUEST";
export const ORDER_REMINDER_MARK_SHOWN_SUCCESS = "ORDER_REMINDER_MARK_SHOWN_SUCCESS";
export const ORDER_REMINDER_MARK_SHOWN_FAIL = "ORDER_REMINDER_MARK_SHOWN_FAIL";
